@service_name= tutorial-demo1
@port = 443
@datasource_name = samplesource
@credentials = 
@container = sample
@index_name= my-search-index-1
@indexer=my-search-indexer-1
@query=$top=10
@api_version=2021-04-30-Preview
@query_key= 
@api_primary_key= 

### データソースの作成
PUT /datasources/{{datasource_name}}?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}

{   
    "description" : "sample datasource",  
    "type" : "azureblob",
    "credentials" : { "connectionString" : "{{credentials}}" },
    "container": {
        "name": "{{container}}"
    }
}

### インデックスの削除
DELETE /indexes/{{index_name}}?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}

### インデックスの作成
PUT /indexes/{{index_name}}?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}

{
  "fields": [
      { "name": "ID", "type": "Edm.String", "key": true, "searchable": false },
      { "name": "content", "type": "Edm.String", "searchable": true, "filterable": false },
      { "name": "metadata_storage_name", "type": "Edm.String", "searchable": false, "filterable": true, "sortable": true  },
      { "name": "metadata_storage_size", "type": "Edm.Int64", "searchable": false, "filterable": true, "sortable": true  },
      { "name": "metadata_storage_content_type", "type": "Edm.String", "searchable": false, "filterable": true, "sortable": true },
      { "name": "file_name", "type": "Edm.String", "searchable": false, "filterable": true, "sortable": true },
      { "name": "url", "type": "Edm.String", "searchable": false, "filterable": true, "sortable": true },
      { "name": "raw", "type": "Edm.String", "searchable": false, "filterable": true, "sortable": true }  
  ]
 }

### インデクサーの削除
DELETE /indexers/{{indexer}}?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}

### インデクサーの作成
PUT /indexers/{{indexer}}?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}

{
    "dataSourceName" : "{{datasource_name}}",
    "targetIndexName" : "{{index_name}}",
    "fieldMappings" :
    [
        {
            "sourceFieldName" : "metadata_storage_name",
            "targetFieldName" : "file_name"
        },
        {
            "sourceFieldName" : "metadata_storage_path",
            "targetFieldName" : "url"
        },
        {
            "sourceFieldName" : "metadata_storage_path",
            "targetFieldName" : "id",
            "mappingFunction" : { 
              "name" : "base64Encode", 
              "parameters" : { "useHttpServerUtilityUrlTokenEncode" : true }
            }
        }
    ]
}


### インデクサーのリセット
POST /indexers/{{indexer}}/reset?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}


### インデクサーの実行
POST /indexers/{{indexer}}/run?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}

### インデクサーのステータス
GET /indexers/{{indexer}}/status?api-version={{api_version}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json  
  api-key: {{api_primary_key}}

### 検索（GET）
GET /indexes/{{index_name}}/docs?api-version={{api_version}}&search={{query}}
  HOST: {{service_name}}.search.windows.net:{{port}}
  Content-Type: application/json
  api-key: {{query_key}}

### 検索 (POST)
POST /indexes/{{index_name}}/docs/search?api-version={{api_version}}
  Content-Type: application/json
  api-key: {{query_key}}

{
    "count": true,
    "search": "Sample",
    "searchMode": "all"
}

### 検索 (POST)
POST /indexes/{{index_name}}/docs/search?api-version={{api_version}}
  Content-Type: application/json
  api-key: {{query_key}}

{
    "count": true,
    "search": "url:'sample' AND content:'test'",
    "queryType": "full" ,
    "searchMode": "all"
}

### 検索 (POST)
POST /indexes/{{index_name}}/docs/search?api-version={{api_version}}
  Content-Type: application/json
  api-key: {{query_key}}

{
    "count": true,
    "search": "NOT url: test AND content:'bbb'",
    "queryType": "full" ,
    "searchMode": "all"
}
